### ISSUE TITLE
Distance Direction produces same ellipse when using semi or full options in pro

### ISSUE THREAD

**Issue by pHill5136** [Esri/distance-direction-addin-dotnet#176]
The distance Direction Ellipse tool produces identical ellipses in pro when choosing semi or full options.
Create Semi ellipse
1. Select Semi for ellipse type
2. click on map pointer tool
3. Select a location on map
4. Set 200000 for the major axis
5. Set 100000 for minor axis
6. select 60 degrees for rotation
7. Click enter to create ellipse
Create full ellipse
8.Select full for ellipse type
9. click on map pointer tool
10. Select a location on map
11. Set 200000 for the major axis
12. Set 100000 for minor axis
13. select 60 degrees for rotation
14. Click enter to create ellipse

Ellipses will be the same size and dimensions

**Comment by pHill5136** [comment]
This is the expected behavior. Closing

**Comment by dfoll** [comment]
While writing doc, I have been following the workflows in the software to make sure that nothing has changed since the original writing of the doc. I have followed @pHill5136 repro steps and saw the same results (using build 1000). 


1. Select Semi for ellipse type
2. Set the center point as "0 0" (using default map coordinates)
3. Set 10 for the major axis
4. Set 3 for minor axis
5. select 0 degrees for rotation
6. Press enter to create ellipse

Create full ellipse

7.Select full for ellipse type
8. Set the Center point as "0 0" (using default map coordinates)
10. Set 10 for the major axis
11. Set 3 for minor axis
12. select 45 degrees for rotation
13. Press enter to create ellipse

both ellipses are the same size, however the one created when "full" was selected should be half the size

![image](https://cloud.githubusercontent.com/assets/5322669/21372580/f4776094-c6cc-11e6-9c39-9317605fb8ed.png)
ellipse draw with "semi" option

![image](https://cloud.githubusercontent.com/assets/5322669/21372586/029de968-c6cd-11e6-9693-d18bf1b5e5bc.png)
ellipse drawn with "full" option

![image](https://cloud.githubusercontent.com/assets/5322669/21372596/13449802-c6cd-11e6-95f8-875c42b4d2cd.png)
measurement of ellipse drawn with "semi" option, this is correct, the "semi-major axis" is 10, as entered

![image](https://cloud.githubusercontent.com/assets/5322669/21372607/2e4e2776-c6cd-11e6-8dcf-f61ce3dd9d66.png)
measurement of ellipse drawn with "full" option, this is incorrect the "major axis" should be only 10, because you entered a value of 10 for major and had the full option selected, however it is still treating the value of 10 as the "semi-major axis", even though the "full" option was selected

**Comment by dfoll** [comment]
NOTE: the minor axis is behaving the same way, i just didn't include screenshots of that because i felt like just showing the major axis behavior illustrated the problem. If this is not clear or there are further questions, please contact me

**Comment by pHill5136** [comment]
fixed this pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/228

**Comment by dfoll** [comment]
verified, using the same values for full and semi, the one generated using full is approximately half the size of the one generated using semi. this is correct
