### ISSUE TITLE
Output needs to be identified/labeled in Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#192]
For ArcGIS Pro the Distance and Direction tools do not show labels for output graphics the same way that ArcMap does. Now we get the graphics drawn on the map, but no labels to tell about the geometry's construction:
![image](https://cloud.githubusercontent.com/assets/3093182/21331530/bb91f63e-c5f7-11e6-8668-d7adee822228.png)

In ArcMap (10.4.1 in the example below) the tools give us the following:
For Lines:
* Bearing (angle)
* Distance

For Circles:
* Radius/Diameter

For Ellipses:
* Major axis length
* Minor axis length
* Orientation angle

![image](https://cloud.githubusercontent.com/assets/3093182/21331603/2edbe816-c5f8-11e6-94cc-b09a6a0fa421.png)

**Comment by mfunk** [comment]
Still an issue at Build 1057 (1/5/2017 @ 9:07 AM) on ArcGIS Pro 1.4.0.7197

**Comment by topowright** [comment]
@pHill5136 Based on the work that was done for the webinar is this something that we could fix?

**Comment by nfeuerstein** [comment]
Labels are still a limitation in Pro.

**Comment by csmoore** [comment]
@kgonzago @pHill5136 - Pro does have a TextSymbol (at least in the latest) - can you explain a little more about the limitation?  

https://pro.arcgis.com/en/pro-app/sdk/api-reference/index.html#topic12379.html

**Comment by lfunkhouser** [comment]
Adding @csmoore comment from duplicate issue #479 on 2/22/2018:

I saw in the Symbology section of ["What's new at Pro 2.1"](http://pro.arcgis.com/en/pro-app/get-started/whats-new-in-arcgis-pro.htm) that "Text elements are now supported within marker symbol layers." so that may also be an option.

Here is an example of how to configure in Pro - not sure how to do programmatically:

![image](https://user-images.githubusercontent.com/3090809/36544816-5d818210-17b5-11e8-8cb1-92db7f5bb045.png)

**Comment by topowright** [comment]
This has been addressed. This issue can be closed.

**Comment by topowright** [comment]
@lfunkhouser
