### ISSUE TITLE
Add warning when user is about to lose data

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#21]
From @mcalamito 

If the user has input information in the Lines tab and begins drawing, a warning should be displayed prompting them that loss of data will occur if the tab is switched to Circles.

**Comment by mfunk** [comment]
Tried this on build 1057 and switching tabs with values still in parameter boxes will clear them out and loose data. However I feel this is a minor issue. At best the boxes would retain the values between tab switching, but then what happens if they want to change all of the values? Adding a "Clear Dialog" button would be too much. I'm in favor of keeping it as-is.

**Comment by topowright** [comment]
This is no longer an issue. Feature persist after they have been drawn on the map when switching between tabs.
