### ISSUE TITLE
Circle tool: Center Point parameter does not handle coordinates entered in Longitude Latitude order (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#218]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21409723/a34a1846-c790-11e6-9d73-e2eb9f3294d4.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21409725/a6a9c0c2-c790-11e6-8abb-d7b05ce6ddbd.png)

**Comment by rjones0** [comment]
I have a fix for this locally, will make pull request when possible.

**Comment by kgonzago** [comment]
Issue fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/498)

**Comment by topowright** [comment]
I have verified this is now showing updated for my default maps units and cursor location in the add-in. I am also able to type in coordinates both long lat and lat long.

**Comment by lfunkhouser** [comment]
Removing closing label, E-verified, until this issue is ready to be closed.

**Comment by ACueva** [comment]
I've verified this works at ArcMap 10.6
![2018-02-26_13-39-10](https://user-images.githubusercontent.com/3093940/36696920-70ae9cd6-1afa-11e8-825a-5b3127415216.png)

Checklist has been updated.
https://github.com/ArcGIS/solutions-defense-test-catalog/commit/12ccc28b5a384fa860fdfa46852465a2288fa198

Removed this issue from known issues.
Left the QC-Doc tag due to the following:
- [ ] This issue needs to have the correct label added to it for the "issues addressed" section.

**Comment by topowright** [comment]
@ACueva I am confused by the last screen shot. Can you add detail of what that should be gleaning from this comment?

**Comment by ACueva** [comment]
Just listing the build number.

**Comment by dfoll** [comment]
is this ready to be moved to review? it has been commented that the issue no longer exists. I verified it is no longer in the known issues list. between the two I think this can be moved to "for review"
