### ISSUE TITLE
Allow user to create unequally spaced rings through keyboard 

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#312]
We allow the user to interactively create unequally spaces rings...
![image](https://cloud.githubusercontent.com/assets/4635490/22665345/4f18f1f4-ec69-11e6-8433-e44b7b717219.png)

It would be very useful to be able to create unequally spaces rings through the keyboard. For user input the user could enter a delimited list of distances, for example...
![image](https://cloud.githubusercontent.com/assets/4635490/22665381/74d152e2-ec69-11e6-9394-40657d550871.png)

**Comment by kgonzago** [comment]
![image](https://user-images.githubusercontent.com/6391826/39197942-c8285444-47b3-11e8-824c-fd7bb5dbf13b.png)

Issue fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/555)

**Comment by BobBooth** [comment]
@kgonzago   what happens if the user includes comma delimiters, as in @elinz original issue text?
Does the input box handle distances with thousands separator commas? With decimal points (1.4, 2.7, 5.9) KM? What if they get mixed? 5,280.0, 2,640.0, 1,320.0 ?

**Comment by kgonzago** [comment]
@BobBooth The logic handles commas, spaces and semicolons as delimiters. Numbers `5,280.0, 2,640.0, 1,320.0` like these will be an issue.

**Comment by kgonzago** [comment]
From our review meeting, it was determined the logic to address #312 will be reverted back due to questions regarding the UI. The team agreed the add-in for Rings should follow what was implemented in the D&D widget:

![image](https://user-images.githubusercontent.com/6391826/39249624-0df046bc-486d-11e8-9463-1922cbfd8889.png)

![image](https://user-images.githubusercontent.com/6391826/39249495-c7cc28ae-486c-11e8-87be-18fd307c2d8e.png)

@ACueva @topowright @dfoll Correct me if I'm wrong.

**Comment by dfoll** [comment]
@lfunkhouser the team met at our review, reviewed the work and made the decision we want to iterate on this work and have the same experience for the add-in as we do for the widge

**Comment by kgonzago** [comment]
I will revert this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/555) which addressed #312

**Comment by topowright** [comment]
Closing this issue all work for ArcMap and ArcGIS Pro will be done in issue #311
