### ISSUE TITLE
Distance Calculation should ignore "From" parameter; current tool produces incorrect results (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#324]
Tested 1.0 release of Military Tools for ArcGIS.

When users perform a distance calculation, the tool should ignore the "From" parameter. The current tool produces incorrect output if the "From" parameter is set to "Diameter". The tool should always create the graphic based radius no matter what the "From" parameter is set to.

For example, if the "From" is set to "Radius" then the tool produces correct output graphic:
24 hours x 60 miles per hour = 1440 miles.
From center point to edge of graphic is 1440 miles (2880 miles diameter)
![image](https://cloud.githubusercontent.com/assets/4635490/23074419/84acaa2c-f4ed-11e6-8379-c45cd1a2b25e.png)

If I use the same center point, time and rate, but the "From" is set to "Diameter", the tool produces incorrect output graphic:
![image](https://cloud.githubusercontent.com/assets/4635490/23074476/afe76c40-f4ed-11e6-88d7-ced3795fbecc.png)

@kgonzago FYI

**Comment by elinz** [comment]
Note: ArcMap addin creates the correct graphic no matter if "From" is set to Radius or Diameter.

**Comment by rjones0** [comment]
@elinz @kgonzago I cannot recreate this in my branch rjones0-207 - pretty sure I spotted it myself and that the fix is included in this PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/326

I've added a note in here to the indicate the fix, just in case it's of interest: https://github.com/Esri/distance-direction-addin-dotnet/pull/326/files

**Comment by elinz** [comment]
@rjones0 @kgonzago Tested on build 23 Feb 2017 09:05. Verified fixed. Closing issue.
