### ISSUE TITLE
Distance and Direction Display issue

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#446]
_From @ACueva on January 12, 2017 22:33_

### Widget
Distance and Direction WAB widget

### Version of widget
2.1 & 2.2

### Bug or Enhancement

Distance and Direction widget gives some weird results with large length values.

### Repo Steps or Enhancement details

navigate to lines tab
change the from select box to 'Distance and Bearing'
enter specific coordinate pair as start point (45, 45) and click enter.
change the length unit to kilometers
enter 20 as the length value

This works.

Change the length value to 20,000 kilometers

![1-12-2017 2-32-25 pm](https://cloud.githubusercontent.com/assets/3093940/21911110/fd2b3620-d8d3-11e6-9493-ebc82da3e768.png)

_Copied from original issue: Esri/solutions-webappbuilder-widgets#781_

**Comment by csmoore** [comment]
_From @adgiles on January 13, 2017 8:49_

@ACueva 

I am not surprised that the tool is giving strange results as the length you are using is longer than the worlds circumference and the geometry engine probably cannot handle it (Have a look at the circle tab and try and draw a circle that is too large).
 
The options we have are:

- Leave it and expect that the users will have some sense when using the tool
- Put a constraint on the input box that doesn't allow such large numbers

@nfeuerstein please advice

**Comment by csmoore** [comment]
_From @nfeuerstein on January 13, 2017 15:23_

Moved milestone to "after-next"

**Comment by topowright** [comment]
Could we possibly put a limit to the length of a line?

**Comment by adgiles** [comment]
@topowright,

I'm personally not a fan of limiting the input values, as undoubtable there will be at some stage a use case that somebody is trying to achieve that falls outside the limit that we set. We would also have to build in all the logic to change the limit depending on what unit of measure is selected, i.e. 20,000 km will probably not work but 20,000 m would be fine.

I don't think that limiting the values would necessarily solve the issue anyway, the underlying problem is that you are trying to show a line that crosses over the pole on to the other side of the globe on a 2D map, so a dog leg has to be drawn to show this. for example if i place a point with a high latitude value and draw a line due north it will cause the same effect, this line is only 1500 km:

![Untitled.png](https://images.zenhubusercontent.com/5a0e6f848a75884b9087cb74/fa3dbe67-c105-4817-889b-dd92a739e885) 

Personally I don't think this is is too much of an issue, if a user wants to enter ridiculous values then they will get strange results. There are probably a number of tools within the platform that will provide strange results given strange inputs.

**Comment by topowright** [comment]
@ACueva is going to double check with the js API team about our thoughts on this issue.

**Comment by ACueva** [comment]
Spoke with @Jianxia regarding this issue.  She will investigate this issue further to determine if it is a WAB or JS API issue.  She'll provide guidance as per her findings.

**Comment by topowright** [comment]
@ACueva will circle back with the JSDev team

**Comment by Jianxia** [comment]
@pspraveenkr @bsvensson  - is it a known issue in jsapi?

**Comment by bsvensson** [comment]
@Jianxia , like @adgiles said: _"if a user wants to enter ridiculous values then they will get strange results"_.  In general, in the API we tend to be forgiving with (ie allow) different inputs.

In a specific widget, a developer could add checks based on the projection used (not everyone limits their map to the earth), and then limit inputs based on that (@csmoore 's option 2). But I would suggest the option 1: `Leave it and expect that the users will have some sense when using the tool`.

**Comment by lfunkhouser** [comment]
Closing as a non-issue.
