### ISSUE TITLE
Switching from Graphics to Features for ArcGIS Pro

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#479]
Instead of using graphics we should switch to features. This will allow us to take advantage of labeling.

**Comment by lfunkhouser** [comment]
@topowright has this been investigated thoroughly? Are we implementing an option to either draw graphics or features? Has any communication or follow up occurred with the Pro team regarding labeling?

**Comment by csmoore** [comment]
I saw in the Symbology section of ["What's new at Pro 2.1"](http://pro.arcgis.com/en/pro-app/get-started/whats-new-in-arcgis-pro.htm) that "Text elements are now supported within marker symbol layers." so that may also be an option.

Here is an example of how to configure in Pro - not sure how to do programmatically:

![image](https://user-images.githubusercontent.com/3090809/36544816-5d818210-17b5-11e8-8cb1-92db7f5bb045.png)

**Comment by csmoore** [comment]
Linking to https://github.com/Esri/distance-direction-addin-dotnet/issues/192 - may be able to close as duplicate

**Comment by lfunkhouser** [comment]
@csmoore Added your comment to #192 and closing this issue as duplicate.
