### ISSUE TITLE
Target Version for ArcMap is not correct

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#499]
When installing the single add-in the number shows incorrectly. If we control this it should be the same as what we do in ArcGIS Pro
![image](https://user-images.githubusercontent.com/5488313/36297801-872ba746-12a9-11e8-81f2-0015c2ae47c7.png)
@lfunkhouser I moved this into this sprint being that it is a bug with Distance and Direction

**Comment by topowright** [comment]
If this is our version of the Add-in this should be 4.0. If we know how to add the build number to this we should do that as well. @kgonzago I remember you looking into this a bit ago, but I do not remember if you understood how to control this for ArcMap

**Comment by kgonzago** [comment]
Correct. I didn't have time to research inclusion of addin build numbers for ArcMap.

**Comment by csmoore** [comment]
@kgonzago and I worked through how to get this to work similar to what was done with the Pro addins. 

Because of all this SCA changes in this repo, we prototype this using visibility and got this working - just use similar changes to get this to work in the other repos when ready: 
https://github.com/Esri/visibility-addin-dotnet/commit/caaf6a65c0d9aac3a35044f1a2856896a85ceaf0

It is very similar to the Pro changes but the syntax is a little arcane because of how xmlpeek task handles custom namespaces (used by the addin config files).

**Comment by lfunkhouser** [comment]
@topowright @csmoore @kgonzago 
This is the version of the ArcMap add-in. The latest released version (June 2017) of this add-in for ArcMap was version 2.1.1. Semantic versioning is used to version the add-ins.
If it is a breaking change, it will be v3.0. 
If there is added functionality, the version of the add-in increments to 2.2.
If there are bug fixes with no new features, the version of the add-in increments to 2.1.2

**Comment by csmoore** [comment]
Added build number to project file similar to Pro addin in PR #505 - can be integrated/tested with Jenkins after PR #505 merged

**Comment by csmoore** [comment]
@ACueva @topowright - this is ready to integrate/test with Jenkins (when build/fileshare working again)

**Comment by lfunkhouser** [comment]
ArcMap did not introduce a breaking change. Added support for various coordinate formats have been included. The version of the ArcMap add-in should be v2.2.

**Comment by lfunkhouser** [comment]
Closing. Verified as fixed during the Review.
