### ISSUE TITLE
Distance and Direction widget will not load into an app

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#510]
WAB 2.7 and 2.8 snapshot 

1. Create a new app
2. Try to load the Distance and Direction widget into the application
**_The widget hangs on the configuration page with the three "working" dots just cycling_**

On 2.7 I was adding our widget in, on 2.8 I just used what was already in WAB.

**Comment by dfoll** [comment]
@adgiles @kgonzago  anything I could be missing? @Dbarnes1 saw the same.

**Comment by adgiles** [comment]
@dfoll I no longer have access to the latest D&D code since it has been moved up to devtopia, so I cannot check

**Comment by adgiles** [comment]
@dfoll

Looks like there are issues with some of the localisation in the settings.js, instead of this.nls it is this.nnls (double n), on the following lines:

76:  title: this.nnls.lineColorLabel,
84:  title: this.nnls.lineWidthLabel,
112:  title: this.nnls.feedbackLabel,
117:  title: this.nnls.textColorLabel,
125:  title: this.nnls.textSizeLabel,
225:  feedbackLabel: this.nnls.feedbackLabel,

I am not sure what @kgonzago fixed in this PR mentioned here: https://github.com/Esri/distance-direction-addin-dotnet/issues/445#issuecomment-367118734

**Comment by kgonzago** [comment]
@dfoll all issues encountered were fixed in this [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/tree/kevi2741-distance-and-direction). Unfortunately that PR has not been merged, sitting as a PR for the past 10 days. Please look at this [branch](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/tree/kevi2741-distance-and-direction) if you want to test

**Comment by BobBooth** [comment]
@kgonzago                      
I think your fixes to the localization string errors fix this issue:
https://github.com/Esri/distance-direction-addin-dotnet/issues/507
If so, could you comment in it, remove the Dev tag?

Issue https://github.com/Esri/distance-direction-addin-dotnet/issues/508 is not addressed, right?

Issue https://github.com/Esri/distance-direction-addin-dotnet/issues/506 is about typographic/formatting issues with ellipse labels.  Probably an easy fix.
@dfoll - FYI

**Comment by kgonzago** [comment]
#506 and #507 can be tested using this [branch](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/tree/kevi2741-distance-and-direction).

#508 is a core WAB issue. An issue will be submitted in Devtopia.

**Comment by dfoll** [comment]
develop branch from devetopia no longer has this issue
