### ISSUE TITLE
Ellipse feature output gets incorrect value for Angle field

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#572]
I used the Ellipse tool to create an ellipse with:
Major Axis: 400
Minor Axis: 200
Angle: 45
The ellipse graphic is created and appears correct.
When I export it to a feature class, the feature is in the same location, same shape. 
However, the Angle attribute has a value of "0.785398163397448" instead of "45". 

The AngleUnit is correctly populated with "Degrees".
![image](https://user-images.githubusercontent.com/3801392/40557913-ba6fc2ea-601f-11e8-8ac4-28dc875c2424.png)

ArcGIS Pro 2.1
Military Tools

**Comment by topowright** [comment]
Waiting to get a pull request from @csmoore

**Comment by csmoore** [comment]
Just to clarify this bug was also showing up in #543 so will be fixed along with that issue which is currently is progress - for details please see: https://github.com/Esri/distance-direction-addin-dotnet/issues/543#issuecomment-393223522 - I would also recommend not verifying this issue until after issue #561 is also complete

**Comment by ACueva** [comment]
And... i should have read @csmoore's comment. Unable to verify until #561 is complete.

**Comment by topowright** [comment]
This was verified in build 13 of Distance and Direction. This is no longer an issues. It was tested in ArcMap and ArcGIS Pro
