### ISSUE TITLE
Separate ArcMap and ArcGIS Pro code

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#684]
To prepare for converting the addin to a Pro-only component going forward, we are making some structural changes to the solution:

1. Removing: ArcMapAddinDistanceAndDirection project/dll
2. Removing: DistanceAndDirectionLibrary project/dll
3. Refactoring the Pro project to remove dependencies on former DistanceAndDirectionLibrary 
    a. remove view inheritance
    b. remove no-longer-needed classes (super/abstract classes)
    c. remove mediator/dispatcher (ex: convert to RelayCommands) 
    d. use Pro styling for Dark Mode support
4. ~~As part of this refactor we would like to also introduce some Interface classes to enable Mock unit testing of large grained classes (ex. viewmodels)~~ (we removed this)
5. As part of this if you notice any hard-coded UI strings that should be converted to Resources (for I18n) please convert these to resources

**Comment by sumitzarkar** [comment]
@dfoll  @lfunkhouser 

We have commited the code for ticket #684 in the branch [CT-SP1-Ticket684](https://github.com/Esri/distance-direction-addin-dotnet/tree/CT-SP1-Ticket684), this includes the code for following points:
1. Removing: ArcMapAddinDistanceAndDirection project/dll
2. Removing: DistanceAndDirectionLibrary project/dll
3. Refactoring the Pro project to remove dependencies on former DistanceAndDirectionLibrary
    a. remove view inheritance

**Comment by sumitzarkar** [comment]
@dfoll @lfunkhouser @csmoore 

We have commited code for following points:
 3. Refactoring the Pro project to remove dependencies on former DistanceAndDirectionLibrary

       b. remove no-longer-needed classes (super/abstract classes)
       c. remove mediator/dispatcher (ex: convert to RelayCommands) 

For point 3.c some implementation is work in progress and will be delivered tomorrow. Due to this you will observe Ellipse is not working in case of Interactive Mode.

We will be completing this and point 3.d in tomorrows code drop.

**Comment by kedarkamat** [comment]
@csmoore @lfunkhouser @dfoll 

For point 4 (unit testing): Do you want us to use any specific testing library or Visual Studio unit test framework?

For point 5 (localization): Do you want us to ensure that the view elements render correct for Hebrew and German or simply remove hardcoded strings and enable switching languages?

**Comment by csmoore** [comment]
@kedarkamat we were planning on using [Moq](https://github.com/moq/moq4) (this would also needed added to the packages.config nuget dependencies).

For 5, we were mainly concerned about hard coded strings in the WPF or message boxes being converted to resources. But if you would like to verify with a just a few resources converted in a small localized resource file that would be great. These values could just be dummy/pseudo values.

I had a quick look at yesterdays drop and it looks like really great progress, I'll probably wait to do a complete testing once 3.c is delivered so I am not writing up any in progress issues, but really nice work so far.

**Comment by kedarkamat** [comment]
@csmoore thanks for your inputs. This would help us share the estimates today.

We planned to do the rest of code drop today. However, there's a minor delay. We will be sharing the complete 3.c tomorrow.

**Comment by sumitzarkar** [comment]
@dfoll @lfunkhouser @csmoore

We have commited code for following points:
3. Refactoring the Pro project to remove dependencies on former DistanceAndDirectionLibrary

           c. remove mediator/dispatcher (ex: convert to RelayCommands)
           d. use Pro styling for Dark Mode support

**Comment by csmoore** [comment]
Great I will give it a test today.

I'm building/testing on 2.2 & 2.5. One thing I wanted to mention in case anyone else tries to build on 2.5. I did have to make 2 changes to the csproj file in last drop. The TargetFrameworkVersion was expected, but not sure why the ResourceDesigner thing just popped up (it might just be my machine)

```xml

ProAppDistanceAndDirectionModule.csproj

   <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>

    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
```

**Comment by kedarkamat** [comment]
@csmoore On analyzing unit tests using Moq, introducing interface classes and services to test events and properties would need considerable code refactoring. Implementing a test base for all the artefacts (viewmodels/models/helpers) would mean considerable efforts. As discussed in our last call, your expectations for this is basic implementation. 

Could you give us a brief idea on what all aspects we would need for a MVP, may be a list of tasks that you want us to perform would help.

**Comment by csmoore** [comment]
@kedarkamat - I was just thinking about adding tests for the large-grained Pro-XXX-ViewModel classes. My hope was to separate the properties and methods that do not Pro dependencies so they could be unit tested. For example, be able to test CircleViewModel.TravelTimeInSeconds outside of Pro.

But I admit this is a bit vague so if needed I can work on an example and clarification.

**Comment by csmoore** [comment]
@kedarkamat I did some basic testing (but didn’t get a chance to thoroughly test) but I did want to give some feedback from reviewing the code.

Things look really good and really simplified the code. A few minor things I noticed that would be good improvements while you are still changing the code are: 

1.	Remove any files/classes no longer used: ex. Common/Mediator.cs
2.	Move values from Constants.cs to SketchTool.cs (since only used there) and remove class
3.	Some WPF elements can use the Pro styles now (noticed on the buttons, but may be other cases)
Style TargetType="Button" BasedOn="{StaticResource TransparentButtonStyle}" 
--> 
Style="{DynamicResource Esri_SimpleButton}"

4.	Some items in the Common folders/namespaces are repeated elsewhere in the projects, so it would clarify things if we can be move them into one folder/namespace. 

Move classes in
  
ProAppDistanceAndDirectionModule.Common 
(1) Model 
(2) ViewModel 
(3) (and any other repeated folders in Common Folder/Namespaces and also elsewhere) 

To:

(1) ProAppDistanceAndDirectionModule.Models
(2) ProAppDistanceAndDirectionModule.ViewModels

Example: 
`ProAppDistanceAndDirectionModule.Common.EditPropertiesViewModel` --> 
`ProAppDistanceAndDirectionModule.ViewModels.EditPropertiesViewModel` folder/namespace

Let me know if you have any questions or if any of this is unclear - thanks again.

**Comment by csmoore** [comment]
@kedarkamat - we tested today and the only new issue I noticed that has been introduced is an issue with the feedback line/circle not following the mouse cursor when the point tool is active (there is a significant lag/delay). 

The source of this issue seems to be here: 

SketchTool.cs - (New) DelayedInvoker vs (previous implementation) DebounceDispatcher

It was a good idea to try this built-in Pro class, but it seems like the DelayedInvoker does not reliable provide the last point like the previous DebounceDispatcher. Not sure if this is a bug in DelayedInvoker or the intended behavior, but we may have to switch back to the previous helper class.

**Comment by sumitzarkar** [comment]
@csmoore @dfoll @lfunkhouser 
We have commited the code for following points:
 - Implemented I18n
 - Implemented feedback mentioned in https://github.com/Esri/distance-direction-addin-dotnet/issues/684#issuecomment-583680136

**Comment by sumitzarkar** [comment]
@csmoore @dfoll @lfunkhouser 
We have commited the code for UAT feedback  mentioned in https://github.com/Esri/distance-direction-addin-dotnet/issues/684#issuecomment-584437025

**Comment by sumitzarkar** [comment]
@csmoore @dfoll @lfunkhouser 

We have submitted the pull request for this ticket [Pull Request Link](https://github.com/Esri/distance-direction-addin-dotnet/pull/685/)

**Comment by sumitzarkar** [comment]
@csmoore @dfoll @lfunkhouser

We have update Distance & Direction addin code to incorporate the changes we did in coordinate conversion addin.  [Commit Link](
https://github.com/Esri/distance-direction-addin-dotnet/commit/cec65979c7708bf8dbbbae6fdc4ca9675030004e)

**Comment by lfunkhouser** [comment]
@OscarVilla1 @csmoore This needs to be tested on our end on Pro 2.6. This is what we are developing this for and needs to be verified on that version.

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll 

We have implemented code for merging resource dictionaires [commit link](https://github.com/Esri/distance-direction-addin-dotnet/pull/686/commits/3d411c5eee18e0245020ca956c1008e9e508c186)

Combine the 2 resource dictionaries:
     a. `ProAppDistanceAndDirectionModule\Common\MAResourceDictionary.xaml`
     b. `ProAppDistanceAndDirectionModule\ProMAResourceDictionary.xaml`

**Comment by csmoore** [comment]
[Verified](https://github.com/ArcGIS/solutions-defense-test-catalog/issues/280)
